// File generated by FlutterFire CLI.
// Contains configuration options for Firebase services.
// You should not manually edit this file - it will be regenerated when you run 'flutterfire configure'.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2hZg6Un7CqcFZvNQfQ_EfcN8yO4CV_s',
    appId: '1:846264121883:web:YOUR_WEB_APP_ID_HERE', // Replace with actual web appId
    messagingSenderId: '846264121883',
    projectId: 'twofour-fef75',
    authDomain: 'twofour-fef75.firebaseapp.com', // Common default format
    storageBucket: 'twofour-fef75.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID_HERE', // Required for web analytics, get from Firebase Console
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2hZg6Un7CqcFZvNQfQ_EfcN8yO4CV_s',
    appId: '1:846264121883:android:539326eeb25adf851996be', // For tm.ran.aiikigai
    messagingSenderId: '846264121883',
    projectId: 'twofour-fef75',
    storageBucket: 'twofour-fef75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2hZg6Un7CqcFZvNQfQ_EfcN8yO4CV_s',
    appId: '1:846264121883:ios:YOUR_IOS_APP_ID_HERE', // Replace with actual iOS appId
    messagingSenderId: '846264121883',
    projectId: 'twofour-fef75',
    storageBucket: 'twofour-fef75.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID_HERE', // Replace with actual iOS clientId
    iosBundleId: 'tm.ran.aiikigai', // Adjust if iOS bundle ID differs
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf2hZg6Un7CqcFZvNQfQ_EfcN8yO4CV_s',
    appId: '1:846264121883:macos:YOUR_MACOS_APP_ID_HERE', // Replace with actual macOS appId
    messagingSenderId: '846264121883',
    projectId: 'twofour-fef75',
    storageBucket: 'twofour-fef75.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID_HERE', // Replace with actual macOS clientId
    iosBundleId: 'tm.ran.aiikigai', // Adjust if macOS bundle ID differs
  );
}